# Generated by Django 4.2.6 on 2023-12-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='stationvideos')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsisi.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stationimages')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsisi.station')),
            ],
        ),
    ]
